csv:
  download:
    baseUrl: ${csvDownloadBaseUrl:https://www.ftc.go.kr/www/downloadBizComm.do?atchFileUrl=dataopen&atchFileNm=}

openapi:
  api:
    key: ${openApiKey:y1AF0a1VYjWFZdiiD5AX9EryBUpASA1AhXouh98R5jwUfnXFkaBZOkT8AebocKnYICAHsi8CpOuco9VTew%2B4TQ%3D%3D}

juso:
  searchapi:
    key: ${jusoSearchApiKey:devU01TX0FVVEgyMDI1MDMyNTE1MTgxMTExNTU3NzE=}

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
