csv:
  download:
    baseUrl: https://www.ftc.go.kr/www/downloadBizComm.do?atchFileUrl=dataopen&atchFileNm=

openapi:
  api:
    key: ${openApiKey}

juso:
  searchapi:
    key: ${jusoSearchApiKey}

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/antock
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create